name = "cf-url-shortener"
main = "src/index.js"
compatibility_date = "2026-01-03"

routes = [
  { pattern = "lzvr.biz.id/*", zone_name = "lzvr.biz.id" }
]

[[kv_namespaces]]
binding = "LINKS"
id = "your-kv-namespace-id-here"

[vars]
TURNSTILE_SITE_KEY = ""
